name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7.41-debian
        
    steps:
      - uses: actions/checkout@v2
    


      - name: Hello hai
        run: echo Hello, hai!

      - name: Run multi
        run: |
          echo hello hello
          echo test, testing
